site_name: CS479 Machine Learning for 3D Data (KAIST, Spring 2025)

theme:
  name: material
  icon:
    logo: material/cube-outline
  features:
    - navigation.tabs
    - navigation.tabs.sticky

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - footnotes
  - meta
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables

plugins:
  - macros

copyright: Copyright &copy; 2025 Minhyuk Sung

nav:
  - Home: index.md
  - Programming Assignments: programming-assignments.md
  - 3D Rendering Contest: 3d-rendering-contest.md

extra:
  analytics:
    provider: google
    property: G-0DGDW2727H
  links:
    lec01: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VmMUZ5TDd5MHU5RW5OT1JpWTZxS0I0Qmc1a3F2SklwZGZuaHpLSFhfckJvamc&cid=60562023B6640282&id=60562023B6640282%21sbec845fdd2f244ef9cd391898eaa281e&parId=60562023B6640282%21s39c180413b784fc88bee11a3ad2a74e5&o=OneUp
    lec02: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VlZlhIanRDcDZsSHFiNHR0bktYNG1RQjNzcDgzTC1mT1ZFWUxvdnhNanhBMFE%5FZT1uZWVub0w&cid=60562023B6640282&id=60562023B6640282%21s3b1ed7e7a74247a9a9be2db67297e264&parId=60562023B6640282%21s39c180413b784fc88bee11a3ad2a74e5&o=OneUp
    lec03: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VXTkJ1MWozYlU5SHN6cld6ZDhWRjQwQmJGTk84RWEzdmNMaktsM1dVOWlQMGc%5FZT1VSTZTMmo&cid=60562023B6640282&id=60562023B6640282%21s58bb41636df7474fb33ad6cddf15178d&parId=60562023B6640282%21s39c180413b784fc88bee11a3ad2a74e5&o=OneUp
    rec02: https://youtu.be/5nwCq8KONRo
