site_name: CS479 Machine Learning for 3D Data (KAIST, Spring 2025)

theme:
  name: material
  icon:
    logo: material/cube-outline
  features:
    - navigation.tabs
    - navigation.tabs.sticky

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - footnotes
  - meta
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables

plugins:
  - macros

copyright: Copyright &copy; 2025 Minhyuk Sung

nav:
  - Home: index.md
  - Programming Assignments: programming-assignments.md
  - 3D Rendering Contest: 3d-rendering-contest.md
  - Guest Lecture 1: guest-lecture-jiahui-huang.md
  - Guest Lecture 2: guest-lecture-songyou-peng.md

extra:
  analytics:
    provider: google
    property: G-0DGDW2727H
  links:
    lec01: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VmMUZ5TDd5MHU5RW5OT1JpWTZxS0I0Qmc1a3F2SklwZGZuaHpLSFhfckJvamc&cid=60562023B6640282&id=60562023B6640282%21sbec845fdd2f244ef9cd391898eaa281e&parId=60562023B6640282%21s39c180413b784fc88bee11a3ad2a74e5&o=OneUp
    lec02: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VlZlhIanRDcDZsSHFiNHR0bktYNG1RQjNzcDgzTC1mT1ZFWUxvdnhNanhBMFE%5FZT1uZWVub0w&cid=60562023B6640282&id=60562023B6640282%21s3b1ed7e7a74247a9a9be2db67297e264&parId=60562023B6640282%21s39c180413b784fc88bee11a3ad2a74e5&o=OneUp
    lec03: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VXTkJ1MWozYlU5SHN6cld6ZDhWRjQwQmJGTk84RWEzdmNMaktsM1dVOWlQMGc%5FZT1VSTZTMmo&cid=60562023B6640282&id=60562023B6640282%21s58bb41636df7474fb33ad6cddf15178d&parId=60562023B6640282%21s39c180413b784fc88bee11a3ad2a74e5&o=OneUp
    lec04: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VaQ0MzQTBYbGZaSXRYYklVU3czS1g4QkxCVUVxZ1pmaldOdkhRenlORU5nNWc%5FZT1OSUlTaHM&cid=60562023B6640282&id=60562023B6640282%21s0ddc8290951748f6b576c8512c37297f&parId=60562023B6640282%21s39c180413b784fc88bee11a3ad2a74e5&o=OneUp
    lec05: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0ViTEQ3Z1lPV2ZWS25pLW5JbnMyM1RNQnNUNUo3YkNaUkRaUHFBWGFIdlFiamc%5FZT1VUWo0V2w&cid=60562023B6640282&id=60562023B6640282%21s06eec3b2590e4af59e2fa7227b36dd33&parId=60562023B6640282%21s39c180413b784fc88bee11a3ad2a74e5&o=OneUp
    lec06: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VjRmc5eTA5TEw1SG8wRWlCVWpwNWtjQjI4NzRFSmpITmRncnllQVV3enN1OGc%5FZT05WDdkQ1A&cid=60562023B6640282&id=60562023B6640282%21s2df760c12c3d47bea341220548e9e647&parId=60562023B6640282%21s39c180413b784fc88bee11a3ad2a74e5&o=OneUp
    lec07: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VWWE0xWnRJakhKR2stUTdKUFpGU2d3QkFfZHBTQ0YzRENCcHNfMll2VGxMalE%5FZT1xWlF5c1c&cid=60562023B6640282&id=60562023B6640282%21s9bd5cc558c48467293e43b24f6454a0c&parId=60562023B6640282%21s39c180413b784fc88bee11a3ad2a74e5&o=OneUp
    lec08: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VUT2JkNlZCNThSRHNNMjN3Q0tEUHNvQnhTMV9qeVRDeFdzdjhqUmZsWUVFd3c%5FZT1nalc1Tzc&cid=60562023B6640282&id=60562023B6640282%21sa5779b33e74143c4b0cdb7c022833eca&parId=60562023B6640282%21s39c180413b784fc88bee11a3ad2a74e5&o=OneUp
    lec09: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VmZ2xVMzZCT3FoQXBvYVVhNVE0ejRJQlhTLXlra3F5WUFZaEZudi1OSS02VUE%5FZT1jOXdQVU0&cid=60562023B6640282&id=60562023B6640282%21s7e5325f83a8140a8a686946b9438cf82&parId=60562023B6640282%21s39c180413b784fc88bee11a3ad2a74e5&o=OneUp
    lec10: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VVbU56eGpXSVp4UHU0YjdEcDQ4M3k0QlJfWWxqUS1qdHhONUZrQ1phNjI4Z1E%5FZT1oYXpRb1c&cid=60562023B6640282&id=60562023B6640282%21s18cf8d4921d64f9cbb86fb0e9e3cdf2e&parId=60562023B6640282%21s39c180413b784fc88bee11a3ad2a74e5&o=OneUp
    lec11: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VVdG5yVzhDRkN0R3ZETG9KZDhPcjVFQi1pUkQzaExTc2dmZ3p4cUNYSDNMMWc%5FZT0zNXdoano&cid=60562023B6640282&id=60562023B6640282%21s6fad674b1402462bbc32e825df0eaf91&parId=60562023B6640282%21s39c180413b784fc88bee11a3ad2a74e5&o=OneUp
    lec12: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VmdzNNaDI4ckk1S3RFYXVxMnlsZ2dFQlFmakpqZDFlanlZVlJGRDh3enQtMkE%5FZT1nVjdMbEw&cid=60562023B6640282&id=60562023B6640282%21s1d3237fcacbc4a8eb446aeab6ca58201&parId=60562023B6640282%21s39c180413b784fc88bee11a3ad2a74e5&o=OneUp
    rec02: https://youtu.be/5nwCq8KONRo
    rec03: https://youtu.be/4iz_SITZOE4
    rec04: https://youtu.be/0oE_S18G8GQ
    rec05: https://youtu.be/XCZPlMv7iKQ
    rec06: https://youtu.be/yCV3_prtIeo
    rec07: https://youtu.be/-bqHPtbjNrc
    rec08: https://youtu.be/SC_X5aQX8Lo
    rec09: https://youtu.be/1nr2MZ_PM-0
    rec10: https://youtu.be/4TtSbEXI_Gg
    rec11: https://youtu.be/8sGdhcIv3l0
    asgmt1: https://github.com/KAIST-Visual-AI-Group/CS479-Assignment-PointNet
    asgmt2: https://github.com/KAIST-Visual-AI-Group/CS479-Assignment-NeRF
    asgmt3: https://github.com/KAIST-Visual-AI-Group/CS479-Assignment-3DGS
    asgmt4: https://github.com/KAIST-Visual-AI-Group/CS479-Assignment-MLS-MS
    demo: https://github.com/KAIST-Visual-AI-Group/CS479-Assignment-NeRF-Applications
    asgmt1_slides: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VlRkFoWV9LRWRaSmduN3RaWlZKWnNzQlExUVlmMktLb3BDMUt3Mkpjd05KNmc%5FZT1aY3A3cmY&cid=60562023B6640282&id=60562023B6640282%21s8f8540e111ca49d6827eed65954966cb&parId=60562023B6640282%21s2c0bb77881d340278e5d198fe134000d&o=OneUp
    asgmt2_slides: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VheTA1aFBhdV9GRWtIck5pS0tTUmhrQkVBWFcwdUYwTnRIQmlhdWNlZ0ozalE%5FZT1Tb1FDaDE&cid=60562023B6640282&id=60562023B6640282%21s13e6b4acbbda44f1907acd88a2924619&parId=60562023B6640282%21s2c0bb77881d340278e5d198fe134000d&o=OneUp
    demo_slides: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VZQVJJbDFnSWZORW1kYzg1bW9GSW9VQnVSdEduLU4tVUo4UjU3UzcxN1Y5c0E%5FZT1YWjlyc0s&cid=60562023B6640282&id=60562023B6640282%21s5d221180216044f399d73ce66a052285&parId=60562023B6640282%21s2c0bb77881d340278e5d198fe134000d&o=OneUp
    asgmt3_slides: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VmdnhSQVY2MkFWTWxYeVdRaG1iVlFRQnY2QWE2MXdCSVFnclFkQmlFeVhUZnc%5FZT0xYjdmZlA&cid=60562023B6640282&id=60562023B6640282%21s0544f1fbd87a4c05957c9642199b5504&parId=60562023B6640282%21s2c0bb77881d340278e5d198fe134000d&o=OneUp
    guest_rec01: https://youtu.be/Z_JPq1jYYf4
    guest_rec02: https://youtu.be/pcTNtDSS7p4
